### ISSUE TITLE
Document authenticating to GCR/GAR

### ISSUE THREAD

**Issue by sethvargo** [google-github-actions/auth#126]
@sethvargo we had a few issues about pushing to GAR/GCR (https://github.com/google-github-actions/auth/issues/104#issuecomment-1004891427, https://github.com/google-github-actions/auth/issues/50#issuecomment-973450688) should we have an example that showcases this?

_Originally posted by @bharathkkb in https://github.com/google-github-actions/auth/issues/123#issuecomment-1028146777_

**Comment by sethvargo** [comment]
@bharathkkb where do you think these should live? I think there's probably more examples, but you're right that this one comes up a lot.

**Comment by bharathkkb** [comment]
Maybe we can add a sample code snippet [here](https://github.com/google-github-actions/auth#examples) and move it over to a workflow repo when we have finalized its location?
