### ISSUE TITLE
Node 16 support on self-hosted runners

### ISSUE THREAD

**Issue by maduq1** [google-github-actions/auth#142]
### TL;DR

When trying to use the action in a self-hosted runner, we get the following:

`Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node16' is not supported, use 'docker' or 'node12' instead.')`

The self-hosted runner is a Debian machine using node 16.

### Expected behavior

The error should not happen, just run the whole workflow.

### Action YAML

```yaml
name: Deploy

on:
  push:
    branches:
      - master

jobs:
    deploy-to-test:
    runs-on: [self-hosted, test-environment]

    needs: [version-bump]

    env:
      SLS_ENV: test

    steps:
     - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: |
          npm ci
          cd db
          npm ci
          cd ..
      - name: Auth in GCloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.PROJECT }}
```

### Log output

```text
Download action repository 'actions/checkout@v2'
Download action repository 'actions/setup-node@v2'
Download action repository 'google-github-actions/auth@v0'
Download action repository 'google-github-actions/setup-gcloud@master'
Download action repository 'rtCamp/action-slack-notify@v2'
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node16' is not supported, use 'docker' or 'node12' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load google-github-actions/auth/v0/action.yml
```

### Additional information

When we remove the specific `auth` step, everything works just fine.

**Comment by sethvargo** [comment]
Hi @maduq1 - you can pin to https://github.com/google-github-actions/auth/releases/tag/v0.4.4, which is the last release that supports Node 12. Node 12 is EOL and will no longer be supported after 2022-04-30.

The error message you're getting is coming from the GitHub Actions runner. Please make sure you're using the latest version. If you continue to get an error after upgrading to the latest version, I would recommend you contact GitHub support. Unfortunately there's nothing we can do in the `auth` action besides restore support for Node 12, but as I mentioned above, it's EOL and will no longer receive security updates soon. Given `auth` relies on cryptography, we cannot take that risk. Additionally, the GitHub managed runners _do_ support Node 16, so I think this should be solvable with an update.

Please let me know if you have any questions.

**Comment by maduq1** [comment]
Hi @sethvargo, I think the problem is just the opposite. Somehow, when pulling the code for this action, there is some sort of requirement to use node 12 somewhere here. 
We have updated our runners and even had the same issue with another action: https://github.com/tool3/bump/pull/17
After updating the dependency there, our workflow worked fine. 

Maybe there's something wrong on our code? Will `uses: google-github-actions/auth@v0` pull the action with node 16 support correctly? Is there an easier way to debug this properly?

**Comment by maduq1** [comment]
Hi @sethvargo sorry for multiple messages. Now I understand! In https://github.com/marketplace/actions/authenticate-to-google-cloud the latest published version is v0.4.3, and the version that only supports node16 is v0.5.0 onwards, so the problem I am experiencing might be because the latest published version is not released?

**Comment by sethvargo** [comment]
Hmm - we've published 0.5.0 and 0.6.0 since then. @bharathkkb any idea why the official action is lagging behind releases? Or @abirismyname?

@maduq1 v0 floats and current targets the same hash as v0.6.0: https://github.com/google-github-actions/auth/tags

**Comment by bharathkkb** [comment]
@abirismyname the release showed the `Publish this Action to the GitHub Marketplace` as checked. I unchecked and checked it again followed by updating the release and it showed up in the marketplace. I had assumed the `Publish this Action to the GitHub Marketplace` was sticky and did that for subsequent new releases?

**Comment by maduq1** [comment]
Something very odd that I receive, apart of the `node12` error, is the following: `Fail to load google-github-actions/auth/v0/action.yml` It looks like it cannot find the file?
I have checked the logs and it looks the sha is right: `Download action repository 'google-github-actions/auth@v0' (SHA:8d125895b958610ec414ca4dae010257eaa814d3)` (this points to v0.6.0)

```Download action repository 'google-github-actions/auth@v0' (SHA:8d125895b958610ec414ca4dae010257eaa814d3)
Download action repository 'google-github-actions/setup-gcloud@v0' (SHA:04141d8a7edfc8c679682f23e7bbbe05cbe32bb3)
Download action repository 'rtCamp/action-slack-notify@v2' (SHA:12e36fc18b0689399306c2e0b3e0f[29](https://git.build.ingka.ikea.com/smaland/smaland_backend/runs/314170?check_suite_focus=true#step:1:29)78b7f1ee7)
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node1[6](https://git.build.ingka.ikea.com/smaland/smaland_backend/runs/314170?check_suite_focus=true#step:1:6)' is not supported, use 'docker' or 'node12' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load google-github-actions/auth/v0/action.yml```

**Comment by sethvargo** [comment]
Hi @maduq1 

That error makes sense. I don't think the self-hosted actions runner supports Node 16 yet. The error specifically says "node 1[6] is not supported". Note we don't control the self-hosted runners or actions package, and Node 12 is headed to EOL shortly.

**Comment by maduq1** [comment]
I've been checking and I think they do support node16. As I mentioned, we had the same problem with another marketplace action https://github.com/tool3/bump/pull/17 and after the fix, everything worked as expected. We were having the very same error.

**Comment by sethvargo** [comment]
Hi @maduq1 

I'm not really sure how to debug this. The error message has weirdly misplaced quotes and the six is in brackets `[6]`. The error message is also clearly saying that "node12" is the only valid value.

Are your self-hosted runners ephemeral?

**Comment by maduq1** [comment]
I don't know either. I think the error message is not totally right, I think it messed up with markdown somehow. 
The quotes are definitely misplaced and duplicated, but the 6 is in place:

> Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node16' is not supported, use 'docker' or 'node12' instead.')
>    at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
>    at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
> Error: Fail to load google-github-actions/auth/v0/action.yml

Our self-hosted runners are not ephemeral, they are Debian VMs that are up all day long. I also made sure to update node in them, and remove any trace of node12. I understand this is hard to debug, my apologies. Should you have any idea about other logging we can look for, just give me a shout. And thanks a lot for checking!

**Comment by sethvargo** [comment]
Do you know what version of the Actions runner you're using on your VMs? Are you using the virtual-environments setup too?

**Comment by maduq1** [comment]
They are running the version `2.283.3`. Regarding virtual-environments, I am not sure what that is (is it related with python? our project is js) so I'd say my answer is no 😅

**Comment by sethvargo** [comment]
Hi @maduq1 - I believe 2.283 is quite behind. [2.285.0](https://github.com/actions/runner/releases/tag/v2.285.0) appears to be the first version where Node 16 was supported. I would recommend updating your runner version. If the [latest version](https://github.com/actions/runner/releases) isn't available, you should reach out to GitHub support.

Re: [virtual-environments](https://github.com/actions/virtual-environments), these are the base machine images that have pre-installed software, etc.

Since 2.283.3 does _not_ support Node 16 per the release notes, the most appropriate action is to update the version of your runners. I'm going to make an update to our readme to hint the minimum version, then I'll close out this issue.

**Comment by maduq1** [comment]
Hi @sethvargo, thanks for all the support. 

Now it's finally working. Our main mistake was referring to the default instructions that appear when clicking on "New Runner" from Github. There the version it suggests is way lower than the latest release, which can be obtained from [here](https://github.com/actions/runner/releases)

Funnily enough, our runners have updated themselves a couple of times (they are not very clean in doing so, we can see the folders where they extract the changes), but didn't update to the latest one 🤷

**Comment by sethvargo** [comment]
@maduq1 - that feels like good feedback to submit to the GitHub Actions team via a support ticket 😄
