### ISSUE TITLE
Wildcard support in iam.workloadIdentityUser mapping with repository

### ISSUE THREAD

**Issue by prakashkgsuk** [google-github-actions/auth#150]
### TL;DR

When we map the repo with service account for impersonation as below -

```
member="principalSet://iam.googleapis.com/${WORKLOAD_IDENTITY_POOL_ID}/attribute.repository/${REPO}"
```

It require us to add every new repo manually to add that as valid repo, can we use some wildcard with the repo name so that every repo that starts with some predefined text is authenticated by default and we don't need to add that manually?
something like this -

```
member="principalSet://iam.googleapis.com/${WORKLOAD_IDENTITY_POOL_ID}/attribute.repository/dummy-repo*"
```

and all the repos starting with title "dummy-repo" should be a part of allowed repos for authentication.
and this feature should also be available in Terraform module (google_service_account_iam_member).

**Comment by sethvargo** [comment]
Hi @prakashkgsuk 

Thank you for opening an issue. You can directly map on any of the [GitHub-published claims](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#understanding-the-oidc-token). 

If you want to do more complex things, you can use an attribute condition to control admission to the pool:

```
--attribute-condition="assertion.repo.startsWith('dummy-repo')"
```

Then you would grant the entire pool permission to impersonate (or further restrict with mapping permissions.

Does that make sense?

**Comment by sethvargo** [comment]
Hey there - I'm going to close this out due to inactivity. If this issue is still occurring or you have new information to provide, please comment and a maintainer will re-open. Thank you!
