### ISSUE TITLE
Enable/Support Token Revocation with RFC7009

### ISSUE THREAD

**Issue by irab** [google-github-actions/auth#165]
### TL;DR

Revoke tokens using [RFC7009](https://datatracker.ietf.org/doc/html/rfc7009) instead of just deleting them from disk.

### Detailed design

Not sure if Google Auth supports RFC 7009, but it would be much better for the cleanup to revoke the token as well as deleting it.

An exfiltrated/exposed token usually has a much longer lifetime than the pipeline. To reduce the window available to a bad actor, it would be great to revoke the token via RFC7009.

### Additional information

https://datatracker.ietf.org/doc/html/rfc7009

**Comment by sethvargo** [comment]
There is no way to revoke OAuth2 tokens for service accounts. The https://oauth2.google.com/revoke endpoint will return the following:

```json
{
  "error": "invalid_request"
  "error_description": "Token is not revocable."
}
```

It's possible to revoke _user_ tokens, but that's a very unlikely use case for GitHub Actions. My recommendation is to keep the token lifetime's as short as possible. You can control the value with the `token_lifetime` input parameter to the action.
