### ISSUE TITLE
Let `gsutil` to support Workload Identity Federation authentications (i.e. GitHub OIDC)

### ISSUE THREAD

**Issue by gfx** [google-github-actions/auth#166]
### TL;DR

It would be nice if `gsutil` supports Workload Identity Federation, or GitHub OIDC. As README says:

> ⚠️ The bq and gsutil tools do no currently support Workload Identity Federation! You will need to use traditional service account key authentication for now.

but I really want to do this. I believe this is a key feature for GitHub Actions.

**Comment by IuryAlves** [comment]
I also had this issue when implementing WIF. The way forward is to use `gcloud alpha storage` instead.

See this [comment](https://github.com/GoogleCloudPlatform/gsutil/issues/1407#issuecomment-1013494373) for more context.

**Comment by IuryAlves** [comment]
> @IuryAlves Ah, thank you! So `gcloud alpha storage` is the next major version of Google Cloud Storage CLI and `gsutil` is no longer activily developed. Hope README describes it.

This seems to be the case. Although I don't think they have feature parity yet.

For my usecase I needed to copy from a bucket to a local path (i.e `gcloud alpha storage cp`) and it worked.

**Comment by sethvargo** [comment]
Hi @gfx and @IuryAlves 

Our team does not control the `bq` or `gsutil` CLIs. There's nothing we can do in our GitHub Action to add support - the owners of those CLI tools need to add support for WIF. You can file a support ticket or technical deal blocker with Google Cloud support to request this functionality.

As pointed out, there's also the `gcloud alpha storage` CLI which is under active development which _does_ support WIF, but might not have 100% feature parity with `gsutil`. Thanks!
