### ISSUE TITLE
Error in generating cloud access token

### ISSUE THREAD

**Issue by SPCSEKOL** [google-github-actions/auth#189]
Hi All,
I have followed the workload identity federation based authentication approach to authenticate my gcp account but, I am getting below error:
```
Error: google-github-actions/auth failed with: retry function failed with 0 attempts: failed to generate Google Cloud access token for ***: {
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}
```
##https://github.com/SPCSEKOL/gcp-boot-demo/runs/6642437534?check_suite_focus=true
Please check.

**Comment by sethvargo** [comment]
Hi @SPCSEKOL 

Thank you for opening an issue. Please follow the [troubleshooting steps](https://github.com/google-github-actions/auth/blob/main/docs/TROUBLESHOOTING.md). As noted in the troubleshooting guide, the most common reason for this error is misconfigured attribute mappings.

If you are unable to resolve the issue after the troubleshooting steps, please open a _new issue_ and use one of our issue templates. This helps us collect the required information to try and reproduce the issue.
