### ISSUE TITLE
Warning "The "create_credentials_file" option is true, but the current GitHub workspace is empty" seems me redundant

### ISSUE THREAD

**Issue by vitalyk-multinarity** [google-github-actions/auth#203]
### TL;DR

I'm using this action for running GCP CLI - for starting and stopping VMs. I'd like to suppress this warning but I don't see a way to do that without checkout my repo.

### Detailed design

```markdown
Warning I get:
The "create_credentials_file" option is true, but the current GitHub workspace is empty. Did you forget to use "actions/checkout" before this step? If you do not intend to share authentication with future steps in this job, set "create_credentials_file" to false.

My job YAML: 

     - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
```

**Comment by sethvargo** [comment]
Hi @vitalyk-multinarity 

There have been a number of issues where users have not used the "actions/checkout" step before the `auth` action. This action relies on the creation of that directory to export credentials. Worse, if a user puts "actions/checkout" _after_ our action, it will delete the exported credential.

This is only a warning and does not affect performance. If you really want the warning to go away, you can create an empty file in `$GITHUB_WORKSPACE`.

**Comment by vitalykarasik** [comment]
> If you really want the warning to go away, you can create an empty file in $GITHUB_WORKSPACE
Somehow I missed this simple  workaround and ran 'checkout' instead...
Many thanks!
