### ISSUE TITLE
How to inject github secret into environment?

### ISSUE THREAD

**Issue by daribock** [google-github-actions/auth#226]
I have this error on every dependabot PR and I don't know how to fix it. Can anyone help me please? 🙇‍♂️

> ![image](https://user-images.githubusercontent.com/57658125/194334725-8abfbf55-d014-47c8-a5ee-d54eaae13357.png)

**Comment by sethvargo** [comment]
Dependabot does not have access to your repository secrets. You must create special secrets for Dependabot. Please note, this is a limitation of GitHub Actions and not related to this repository. You can file feedback for GitHub at https://github.com/community/community

https://docs.github.com/en/rest/dependabot/secrets

**Comment by daribock** [comment]
Okay thank you for the feedback. 👍
