### ISSUE TITLE
Documentation missing key point

### ISSUE THREAD

**Issue by joshgc** [google-github-actions/auth#247]
### TL;DR

IIUC self-hosted runners on some GCP compute environment most likely do *not* need to use workload identiy right? We use the standard setup-gcloud and then `gcloud auth list` and `gcloud auth print-access-token` WAI.

### Expected behavior

If my understanding is correct can we add a critical sentence or two to this repo's README.md?

### Action YAML

```yaml
No yaml
```

**Comment by joshgc** [comment]
I appreciate your understanding of the docs Seth. But thats not how the google search for "get gcloud on gha to work" understand the doc structure. This README.md is a top hit, that both me and my SWE manager landed on. And we're both experienced GCP users and we both spent an hour trying to follow these instructions before we went "oh duh this is all not needed".

What does it cost to add a sentence that says "This approach probably is not needed if you're using self-hosted runners on a GCP environment". The doc as it stands comes across as definitive: "Workload Identity Federation is the recommended approach" lacks any conditionals and it lacks any references to the parent documentation that contains the caveat you mentioned in this issue before closing it.

**Comment by sethvargo** [comment]
Hi @joshgc - it's more nuanced than that. The reason it's documented in the associated READMEs is that not _all_ things support Application Default Credentials discovery (and therefore do not detect the metadata server information when using self-hosted runners on GCP).

Furthermore, while you don't _need_ to use this action for self-hosted runners, there are use cases where you might want to use it. For example, the default machine service account might have no permissions on GCP and then rely on WIF to elevate privilege based on workflow attributes. The self-hosted runners could be in a different GCP project with domain-restricted sharing or VPC service controls. The self-hosted runners could be on another cloud provider.

It's incorrect to say that this GitHub Action is mutually exclusive with self-hosted runners. The decision is extremely nuanced and requires information about the installation environment. Self-hosted runners represent an extremely small fraction of the customer base and also corresponds to the most advanced use cases. I'm not supportive of putting references to these advanced use cases in a general-purpose README and risk losing or misleading readers down an unnecessary path. The cost is non-zero, and we don't want users to go on a 50 minute detour reading about self-hosted runners when they land on our README.
