### ISSUE TITLE
Include how to interoperate with the iam.workloadIdentityPoolProviders org policy constraint

### ISSUE THREAD

**Issue by andrewpollock** [google-github-actions/auth#257]
### TL;DR

https://cloud.google.com/iam/docs/manage-workload-identity-pools-providers discusses how to restrict which workload identity pool providers may be permitted, but doesn't go into a detailed example for when it's GitHub.

### Additional information

Please enhance https://github.com/google-github-actions/auth#setting-up-workload-identity-federation to also discuss what needs to be set for the `iam.workloadIdentityPoolProviders` organization policy constraint.

**Comment by andrewpollock** [comment]
@ianlewis FYI

**Comment by ianlewis** [comment]
I assume this is something like 

```
gcloud resource-manager org-policies allow constraints/iam.workloadIdentityPoolProviders \
     https://token.actions.githubusercontent.com --organization=ORGANIZATION_NUMBER
```

**Comment by sethvargo** [comment]
https://github.com/google-github-actions/auth/pull/258 as a little blurb. We don't intend to be a replacement for the Google Cloud documentation though, and this is a somewhat advanced use case. I would recommend filing an internal docs bug as well.

**Comment by andrewpollock** [comment]
Cheers, I've ping you on the corresponding internal docs bug as an FYI.
