### ISSUE TITLE
README: add explicit warning that GCP project number (not project id) is required in workload_identity_provider

### ISSUE THREAD

**Issue by revero-doug** [google-github-actions/auth#269]
### TL;DR

it took some digging through issues to realize that using project number rather than project id is not just a recommendation but a requirement. adding an explicit warning to the README would likely help other users.

### Expected behavior

the README includes an explicit warning that the GCP project number must be used in `workload_identity_provider`

### Observed behavior

the README says to use project number, but does not address that project id will result in 400 errors due to invalid audience

### Action YAML

```yaml
# n/a
```

**Comment by sethvargo** [comment]
Hi @revero-doug 

This is specifically mentioned in the README and troubleshooting steps.

<img width="587" alt="screenshot-20230308-i2GGFlQK@2x" src="https://user-images.githubusercontent.com/408570/223765063-ceb2862a-d16a-4566-a833-0efc392198d2.png">

<img width="613" alt="screenshot-20230308-5RGoUxSZ@2x" src="https://user-images.githubusercontent.com/408570/223765123-a7a33389-e1f6-44b2-b540-fcdf2a5bec2c.png">
