### ISSUE TITLE
Question about applying this action to visit GoogleScholar in GitHub workflow

### ISSUE THREAD

**Issue by WenjieDu** [google-github-actions/auth#301]
Hi, I tried to visit GoogleScholar within a GitHub workflow but got rejected with following message

> Our systems have detected unusual traffic from your computer network.  Please try your request again later. 
Why did this happen? This page appears when Google automatically detects requests coming from your computer network which appear to be in violation of the. The block will expire shortly after those requests stop. This traffic may have been sent by malicious software, a browser plug-in, or a script that sends automated requests. If you share your network connection, ask your administrator for help — a different computer using the same IP address may be responsible. 

I'm thinking, is it possible for me to utilize this auth action to get access to GoogleScholar in a workflow?
Thank you very much in advance!

**Comment by sethvargo** [comment]
Hi @WenjieDu 

Please provide your complete GitHub Actions YAML and the [GitHub Action debug logs](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging).

**Comment by WenjieDu** [comment]
Hi @sethvargo, thank you very much for timely response!

Please take a look at this [action log](https://github.com/WenjieDu/Google_Scholar_Badge_Generator/actions/runs/4834426537/jobs/8615632507#step:6:423), and here is [the config yml](https://github.com/WenjieDu/Google_Scholar_Badge_Generator/actions/runs/4834426537/workflow).

**Comment by sethvargo** [comment]
Hi @WenjieDu 

I cannot provide support for this issue, because scraping Google Scholar articles is a violation of [Google's Terms of Service](https://policies.google.com/terms?hl=en).

**Comment by WenjieDu** [comment]
@sethvargo Got it. Thank you.
