### ISSUE TITLE
workload identity federation in gcp for multiple projects

### ISSUE THREAD

**Issue by esmaeilram** [google-github-actions/auth#322]
### TL;DR

i set up workload identity federation for a couple of projects in GCP. can i set up workload identity federation for multiple projects? 

can I do it by one service account between the GCP projects? how?

**Comment by GregoireW** [comment]
I'm not sure to understand what is really your question, but it is close to some question I got in my organization so I will try this answer. 

Are you asking for this action to authenticate multiple service account at once? 

If so, imagine this:  You want to travel to multiple country. Will you ask for multiple passport with potentially different name   or will you ask for 1 passport and put on it multiple visa.  
If you are a normal person then you have 1 passport (1 identity) and you ask for multiple visa on it (multiple permission). 

You CI job should work the same way:  you should have 1 identity (let say the service account my-ci@my-project ) and you can ask for this service account multiple permission  like access the pubsub  XXX on project  io_project,  read access on big query table in project  bi_project,   kubernetes deployment permission on cluster YYY on project apps_project  and so on and so on.   

It is easier to manage / control / use the permission this way.

**Comment by sethvargo** [comment]
Hi there. This issue tracker is for questions related to the GitHub Action for authenticating to Google Cloud. For general Google Cloud questions, please see https://cloud.google.com/support. Thanks!
