### ISSUE TITLE
Provide `principalSet` as an IAM permission example for Direct Workload Identity Federation

### ISSUE THREAD

**Issue by esciara** [google-github-actions/auth#416]
### TL;DR

Can't find how to set `principalSet` as an IAM permission with Direct Workload Identity Federation.

### Detailed design

In the current [EXAMPLES.md doc](https://github.com/google-github-actions/auth/blob/71fee32a0bb7e97b4d33d548e7d957010649d8fa/docs/EXAMPLES.md), it is mentioned that

> Google Cloud Resources must have the Workload Identity Pool as a `principalSet` as an IAM permission.

I could not find an example of how to set this IAM permission with the `principalSet`. Could you add an example in this doc?

**Comment by sethvargo** [comment]
It's step 5 in the README, for example:

```
principalSet://iam.googleapis.com/${WORKLOAD_IDENTITY_POOL_ID}/attribute.repository/${REPO}
```

![Image](https://github.com/google-github-actions/auth/assets/408570/33710a41-fa39-4cac-b5c1-9c6700f54ffb)
