### ISSUE TITLE
Please provide Terraform templates

### ISSUE THREAD

**Issue by erichiggins** [google-github-actions/auth#428]
### TL;DR

The prerequisite instructions to allow this action to work are needlessly complex and difficult to get right. Providing Terraform templates will help to automate these steps.

### Detailed design

I don't.

### Additional information

It's really really really challenging and time consuming to get this all configured correctly. Using GCP used to be a breeze, now I'm spending hours and days just trying to get the authorization steps working for a simple deploy pipeline

**Comment by sethvargo** [comment]
Hi @erichiggins - you can see the Terraform configurations we used to configure all the CI/CD and GCP projects for these GitHub Actions at https://github.com/google-github-actions/test-infra.
