### ISSUE TITLE
Domain-Wide Delegation with id_token

### ISSUE THREAD

**Issue by RobertOstermann** [google-github-actions/auth#445]
### TL;DR

I noticed in the `access_token` format there is an option `access_token_subject` which allows the access token to impersonate a user's email address. I do not see a similar option for `id_token`. Is it possible to generate an `id_token` impersonating a different user's email address using Domain-Wide Delegation?

**Comment by sethvargo** [comment]
No, DWD only works for OAuth tokens since it's a feature of oauth. It's not available for id tokens.
