### ISSUE TITLE
403s trying to run this action

### ISSUE THREAD

**Issue by mattmoor** [google-github-actions/auth#78]
### TL;DR

Getting 403s trying to experiment with OIDC-based workload identities

### Expected behavior

Action runs successfully, prints list of images, all is merry.

### Observed behavior

I get a 403 executing this action:

```
Error: google-github-actions/auth failed with: Error: Failed to generate Google Cloud access token for gha-test-account-5@mattmoor-chainguard.iam.gserviceaccount.com: {
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}
```

### Action YAML

```yaml
I created a gist here: https://gist.github.com/mattmoor/04a46b31024322b4a95e49cd15a18ccd

The script creates everything and is based on this (thanks to Justin Beckwith): https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/buildsetup.sh

The other half is the yaml you seek.
```

### Additional information

There was already some back-and-forth with @sethvargo on twitter here: https://twitter.com/sethvargo/status/1468785218777665539

**Comment by bharathkkb** [comment]
Hi @mattmoor 
I believe you are missing the `attribute.repository=assertion.repository` mapping in the pool.

**Comment by mattmoor** [comment]
Cool, I'll try that out and report back.

**Comment by mattmoor** [comment]
That was it!

I'd recommend changing the full command in step `7.` to include this [here](https://github.com/google-github-actions/auth#setting-up-workload-identity-federation) as the trailing bit is easy to miss.

I also found the warning on step `8.` mildly terrifying, so perhaps the first command shown under each of these things should be changed towards better "default" behavior 🙏

**Comment by sethvargo** [comment]
https://github.com/google-github-actions/auth/commit/d03480e8adf23ba8516d4c7ab68bc68999d5f0ae
