### ISSUE TITLE
Consider publishing a v1 tag

### ISSUE THREAD

**Issue by sethvargo** [google-github-actions/auth#80]
### TL;DR

Many Actions (including the GitHub ones) publish a `vX` tag and force-push to that tag on changes. Instead of going around and updating READMEs, I wonder if we're better off creating a `v1` tag and force-pushing there (in addition to tagged releases).

### Detailed design

```markdown
git tag -a -s -m v0.x.y v0.x.y && git push origin refs/tags/v0.x.y
git tag -d v1 && git tag -a -s -m v1 v1 && git push -f origin refs/tags/v1
```

**Comment by sethvargo** [comment]
@averikitsch @bharathkkb thoughts?

**Comment by bharathkkb** [comment]
> git tag -a -s -m v0.x.y v0.x.y && git push origin refs/tags/v0.x.y

@sethvargo will we still continue tagging 0.x.y? If so, I think we should tag and force push a v0 tag until we are ready for v1.0.0.

**Comment by sethvargo** [comment]
Yea, we can do `v0` too. More of a question of "should we violate the promise of git tags and force-push over them"?

**Comment by sethvargo** [comment]
https://github.com/google-github-actions/auth/commit/d03480e8adf23ba8516d4c7ab68bc68999d5f0ae
